version: '3'
services:
  auth-db:
    container_name: cube-auth-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: cube-auth
      POSTGRES_PASSWORD: cube-auth
      POSTGRES_DB: cube-auth

  account-db:
    container_name: cube-account-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: cube-account
      POSTGRES_PASSWORD: cube-account
      POSTGRES_DB: cube-account

  zookeeper:
    container_name: cube-zookeeper
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: cube-kafka
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  auth:
    depends_on:
      - 'auth-db'
      - 'kafka'

  account:
    depends_on:
      - 'account-db'
      - 'kafka'
