version: '3'
services:
  auth:
    container_name: cube-auth
    build:
      context: ./apps/auth
      args:
        - PORT=80
    image: cube/auth
    env_file:
      - './apps/auth/.env'

  account:
    container_name: cube-account
    build:
      context: ./apps/account
      args:
        - PORT=80
    image: cube/account
    env_file:
      - './apps/account/.env'

  proxy:
    container_name: cube-proxy
    build:
      context: ./apps/proxy
    image: cube/proxy
    ports:
      - 80:80
    depends_on:
      - auth
