version: '3'
services:
  auth-db:
    container_name: cube-auth-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: cube-auth
      POSTGRES_PASSWORD: cube-auth
      POSTGRES_DB: cube-auth

  account-db:
    container_name: cube-account-db
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: cube-account
      POSTGRES_PASSWORD: cube-account
      POSTGRES_DB: cube-account

  redis:
    container_name: cube-redis
    image: redis
    ports:
      - 6379:6379

  auth:
    depends_on:
      - 'auth-db'
      - 'redis'

  account:
    depends_on:
      - 'account-db'
      - 'redis'

  jobs:
    depends_on:
      - 'redis'
