version: '3'
services:
  auth-db:
    container_name: trxit-auth-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: trxit-auth
      POSTGRES_PASSWORD: trxit-auth
      POSTGRES_DB: trxit-auth

  account-db:
    container_name: trxit-account-db
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: trxit-account
      POSTGRES_PASSWORD: trxit-account
      POSTGRES_DB: trxit-account

  redis:
    container_name: trxit-redis
    image: redis
    ports:
      - 6379:6379

  auth:
    depends_on:
      - 'auth-db'
      - 'redis'

  account:
    depends_on:
      - 'account-db'
      - 'redis'

  jobs:
    depends_on:
      - 'redis'
